skip_commits:
  message: /doco|Merge pull request.*/
image:
- Visual Studio 2019
build_script:
  - dotnet build src --configuration Release
  - dotnet test src --configuration Release --no-build --no-restore
test: off
artifacts:
- path: nugets\**\*.nupkg
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }